export const AnimationVariantType = {
    DRAWER_TOP: 'DRAWER_TOP',
    DRAWER_BOTTOM: 'DRAWER_BOTTOM',
    DRAWER_LEFT: 'DRAWER_LEFT',
    DRAWER_RIGHT: 'DRAWER_RIGHT',
    FADE: 'FADE',
    MOBILE: 'MOBILE',
    NOTIFICATION_BOTTOM_RIGHT: 'NOTIFICATION_BOTTOM_RIGHT',
    NOTIFICATION_BOTTOM_LEFT: 'NOTIFICATION_BOTTOM_LEFT',
    NOTIFICATION_TOP_RIGHT: 'NOTIFICATION_TOP_RIGHT',
    NOTIFICATION_TOP_LEFT: 'NOTIFICATION_TOP_LEFT',
    NOTIFICATION_MOBILE: 'NOTIFICATION_MOBILE',
    SCALE: 'SCALE',
    SLIDE_UP: 'SLIDE_UP',
    SLIDE_DOWN: 'SLIDE_DOWN',
    SLIDE_RIGHT: 'SLIDE_RIGHT',
    SLIDE_LEFT: 'SLIDE_LEFT',
} as const

export type AnimationVariantType = (typeof AnimationVariantType)[keyof typeof AnimationVariantType]
