export const LanguageKeyType = {
    DE: 'de',
    EN: 'en',
    ES: 'es',
    FR: 'fr',
    IT: 'it',
    JA: 'ja',
    ZH: 'zh',
    RU: 'ru',
    KO: 'ko',
    AR: 'ar',
    PT: 'pt',
    HI: 'hi',
    BN: 'bn',
    PA: 'pa',
    VI: 'vi',
    UR: 'ur',
    TR: 'tr',
    NL: 'nl',
    SV: 'sv',
    NO: 'no',
    DA: 'da',
    FI: 'fi',
    EL: 'el',
    HE: 'he',
    HU: 'hu',
    CS: 'cs',
    PL: 'pl',
    RO: 'ro',
    SK: 'sk',
    TH: 'th',
} as const

export type LanguageKeyType = (typeof LanguageKeyType)[keyof typeof LanguageKeyType]
